on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE: ghcr.io/${{ github.repository }}

    steps:
      - run: echo 'The secret is ${{ secrets.SECRET }}'
      - run: docker login ghcr.io -u token -p ${{ github.token }}
      - run: docker pull ${{ env.IMAGE }} 
      - run: docker push ${{ env.IMAGE }} 
